import { readonly, ref } from 'vue'
import { fetchTiposDocumento, submitRegistration } from '../services/registration.api'
import { mapTiposDocumentoToSelectOptions } from '../services/registration.mappers'
import type { RegistrationFormData, SelectOption } from '../types/registration.types'

const tipoOptionsState = ref<SelectOption[]>([])
const isLoadingTipos = ref(false)
const tiposError = ref<string | null>(null)
let hasLoadedTipos = false

export function useRegistrationStore() {
  const isSubmitting = ref(false)
  const feedbackMessage = ref<string | null>(null)

  const loadTiposDocumento = async () => {
    if (hasLoadedTipos || isLoadingTipos.value) {
      return
    }

    isLoadingTipos.value = true
    tiposError.value = null

    try {
      const tipos = await fetchTiposDocumento()
      tipoOptionsState.value = mapTiposDocumentoToSelectOptions(tipos)
      hasLoadedTipos = true
    } catch (error) {
      console.error(error)
      tiposError.value = 'No pudimos cargar los tipos de documento.'
    } finally {
      isLoadingTipos.value = false
    }
  }

  const submit = async (payload: RegistrationFormData) => {
    isSubmitting.value = true
    feedbackMessage.value = null

    try {
      const response = await submitRegistration(payload)
      feedbackMessage.value = response.message
      return response
    } finally {
      isSubmitting.value = false
    }
  }

  const departamentoOptions = ref<SelectOption[]>([
    { label: 'Amazonas', value: 'amazonas' },
    { label: 'Antioquia', value: 'antioquia' },
    { label: 'Arauca', value: 'arauca' },
    { label: 'Atlántico', value: 'atlantico' },
    { label: 'Bolívar', value: 'bolivar' },
    { label: 'Boyacá', value: 'boyaca' },
    { label: 'Caldas', value: 'caldas' },
    { label: 'Caquetá', value: 'caqueta' },
    { label: 'Casanare', value: 'casanare' },
    { label: 'Cauca', value: 'cauca' },
    { label: 'Cesar', value: 'cesar' },
    { label: 'Chocó', value: 'choco' },
    { label: 'Córdoba', value: 'cordoba' },
    { label: 'Cundinamarca', value: 'cundinamarca' },
    { label: 'Guainía', value: 'guainia' },
    { label: 'Guaviare', value: 'guaviare' },
    { label: 'Huila', value: 'huila' },
    { label: 'La Guajira', value: 'laguajira' },
    { label: 'Magdalena', value: 'magdalena' },
    { label: 'Meta', value: 'meta' },
    { label: 'Nariño', value: 'narino' },
    { label: 'Norte de Santander', value: 'nortesantander' },
    { label: 'Putumayo', value: 'putumayo' },
    { label: 'Quindío', value: 'quindio' },
    { label: 'Risaralda', value: 'risaralda' },
    { label: 'San Andrés y Providencia', value: 'sanandres' },
    { label: 'Santander', value: 'santander' },
    { label: 'Sucre', value: 'sucre' },
    { label: 'Tolima', value: 'tolima' },
    { label: 'Valle del Cauca', value: 'valledelcauca' },
    { label: 'Vaupés', value: 'vaupes' },
    { label: 'Vichada', value: 'vichada' }
  ])

  // Municipios por departamento - estructura básica que puedes llenar
  const municipiosPorDepartamento: Record<string, SelectOption[]> = {
    amazonas: [
      { label: 'Leticia', value: 'leticia' },
      { label: 'Puerto Nariño', value: 'puerto-narino' },
      { label: 'La Chorrera', value: 'la-chorrera' },
      { label: 'La Pedrera', value: 'la-pedrera' },
      { label: 'El Encanto', value: 'el-encanto' },
      { label: 'Tarapacá', value: 'tarapaca' },
      { label: 'Puerto Alegría', value: 'puerto-alegria' },
      { label: 'Puerto Arica', value: 'puerto-arica' },
      { label: 'Puerto Santander', value: 'puerto-santander' },
      { label: 'Miriti-Paraná', value: 'miriti-parana' },
      { label: 'Araracuara', value: 'araracuara' },
      { label: 'Puerto Córdova', value: 'puerto-cordova' },
      { label: 'Santa Sofía', value: 'santa-sofia' },
      { label: 'Jardín de la Selva', value: 'jardin-de-la-selva' },
      { label: 'San Pedro de los Lagos', value: 'san-pedro-de-los-lagos' },
      { label: 'San Antonio del Içá', value: 'san-antonio-del-ica' },
      { label: 'La Libertad', value: 'la-libertad' },
      { label: 'Puerto Esperanza', value: 'puerto-esperanza' },
      { label: 'Puerto Remanso', value: 'puerto-remanso' },
      { label: 'Puerto Nápoles', value: 'puerto-napoles' },
    ],
    antioquia: [
      { label: 'Medellín', value: 'medellin' },
      { label: 'Bello', value: 'bello' },
      { label: 'Itagüí', value: 'itagui' },
      { label: 'Envigado', value: 'envigado' },
      { label: 'Rionegro', value: 'rionegro' },
      { label: 'Apartadó', value: 'apartado' },
      { label: 'Turbo', value: 'turbo' },
      { label: 'Caucasia', value: 'caucasia' },
      { label: 'Sabaneta', value: 'sabaneta' },
      { label: 'La Estrella', value: 'la-estrella' },
      { label: 'Copacabana', value: 'copacabana' },
      { label: 'Girardota', value: 'girardota' },
      { label: 'Caldas', value: 'caldas' },
      { label: 'Puerto Berrío', value: 'puerto-berrio' },
      { label: 'Yarumal', value: 'yarumal' },
      { label: 'Santa Rosa de Osos', value: 'santa-rosa-de-osos' },
      { label: 'San Pedro de los Milagros', value: 'san-pedro-de-los-milagros' },
      { label: 'Amagá', value: 'amaga' },
      { label: 'Fredonia', value: 'fredonia' },
      { label: 'La Ceja', value: 'la-ceja' },
    ],
    arauca: [
      { label: 'Arauca', value: 'arauca' },
      { label: 'Tame', value: 'tame' },
      { label: 'Saravena', value: 'saravena' },
      { label: 'Arauquita', value: 'arauquita' },
      { label: 'Fortul', value: 'fortul' },
      { label: 'Cravo Norte', value: 'cravo-norte' },
      { label: 'Puerto Rondón', value: 'puerto-rondon' },
      { label: 'La Esmeralda', value: 'la-esmeralda' },
      { label: 'El Troncal', value: 'el-troncal' },
      { label: 'Panamá de Arauca', value: 'panama-de-arauca' },
      { label: 'Flor Amarillo', value: 'flor-amarillo' },
      { label: 'Todos Santos', value: 'todos-santos' },
      { label: 'La Paz', value: 'la-paz' },
      { label: 'Canoas', value: 'canoas' },
      { label: 'Caracol', value: 'caracol' },
      { label: 'Corocito', value: 'corocito' },
      { label: 'El Caracol', value: 'el-caracol' },
      { label: 'Caño Limón', value: 'cano-limon' },
      { label: 'Mata Oscura', value: 'mata-oscura' },
      { label: 'Botalón', value: 'botalon' },
    ],
    atlantico: [
      { label: 'Barranquilla', value: 'barranquilla' },
      { label: 'Soledad', value: 'soledad' },
      { label: 'Malambo', value: 'malambo' },
      { label: 'Galapa', value: 'galapa' },
      { label: 'Sabanalarga', value: 'sabanalarga' },
      { label: 'Baranoa', value: 'baranoa' },
      { label: 'Puerto Colombia', value: 'puerto-colombia' },
      { label: 'Polonuevo', value: 'polonuevo' },
      { label: 'Ponedera', value: 'ponedera' },
      { label: 'Santo Tomás', value: 'santo-tomas' },
      { label: 'Palmar de Varela', value: 'palmar-de-varela' },
      { label: 'Candelaria', value: 'candelaria' },
      { label: 'Campo de la Cruz', value: 'campo-de-la-cruz' },
      { label: 'Manatí', value: 'manati' },
      { label: 'Luruaco', value: 'luruaco' },
      { label: 'Juan de Acosta', value: 'juan-de-acosta' },
      { label: 'Tubará', value: 'tubara' },
      { label: 'Usiacurí', value: 'usiacuri' },
      { label: 'Repelón', value: 'repelon' },
      { label: 'Piojó', value: 'piojo' },
    ],
    bolivar: [
      { label: 'Cartagena', value: 'cartagena' },
      { label: 'Magangué', value: 'magangue' },
      { label: 'Turbaco', value: 'turbaco' },
      { label: 'Arjona', value: 'arjona' },
      { label: 'El Carmen de Bolívar', value: 'el-carmen-de-bolivar' },
      { label: 'San Juan Nepomuceno', value: 'san-juan-nepomuceno' },
      { label: 'Mompox', value: 'mompox' },
      { label: 'Santa Rosa', value: 'santa-rosa' },
      { label: 'Villanueva', value: 'villanueva' },
      { label: 'Turbana', value: 'turbana' },
      { label: 'María La Baja', value: 'maria-la-baja' },
      { label: 'Mahates', value: 'mahates' },
      { label: 'San Estanislao', value: 'san-estanislao' },
      { label: 'Soplaviento', value: 'soplaviento' },
      { label: 'Calamar', value: 'calamar' },
      { label: 'Cicuco', value: 'cicuco' },
      { label: 'San Cristóbal', value: 'san-cristobal' },
      { label: 'Pinillos', value: 'pinillos' },
      { label: 'Morales', value: 'morales' },
      { label: 'Arenal', value: 'arenal' },
    ],
    boyaca: [
      { label: 'Tunja', value: 'tunja' },
      { label: 'Duitama', value: 'duitama' },
      { label: 'Sogamoso', value: 'sogamoso' },
      { label: 'Chiquinquirá', value: 'chiquinquira' },
      { label: 'Paipa', value: 'paipa' },
      { label: 'Moniquirá', value: 'moniquira' },
      { label: 'Samacá', value: 'samaca' },
      { label: 'Villa de Leyva', value: 'villa-de-leyva' },
      { label: 'Nobsa', value: 'nobsa' },
      { label: 'Garagoa', value: 'garagoa' },
      { label: 'Soatá', value: 'soata' },
      { label: 'Guateque', value: 'guateque' },
      { label: 'Puerto Boyacá', value: 'puerto-boyaca' },
      { label: 'Chiscas', value: 'chiscas' },
      { label: 'Miraflores', value: 'miraflores' },
      { label: 'Cerinza', value: 'cerinza' },
      { label: 'Belén', value: 'belen' },
      { label: 'Corrales', value: 'corrales' },
      { label: 'Santa Rosa de Viterbo', value: 'santa-rosa-de-viterbo' },
      { label: 'Sáchica', value: 'sachica' },
    ],
    caldas: [
      { label: 'Manizales', value: 'manizales' },
      { label: 'La Dorada', value: 'la-dorada' },
      { label: 'Chinchiná', value: 'chinchina' },
      { label: 'Villamaría', value: 'villamaria' },
      { label: 'Riosucio', value: 'riosucio' },
      { label: 'Anserma', value: 'anserma' },
      { label: 'Supía', value: 'supia' },
      { label: 'Neira', value: 'neira' },
      { label: 'Pensilvania', value: 'pensilvania' },
      { label: 'Salamina', value: 'salamina' },
      { label: 'Aguadas', value: 'aguadas' },
      { label: 'Aranzazu', value: 'aranzazu' },
      { label: 'Filadelfia', value: 'filadelfia' },
      { label: 'Marquetalia', value: 'marquetalia' },
      { label: 'Marulanda', value: 'marulanda' },
      { label: 'Norcasia', value: 'norcasia' },
      { label: 'Pácora', value: 'pacora' },
      { label: 'Palestina', value: 'palestina' },
      { label: 'Samaná', value: 'samana' },
      { label: 'Victoria', value: 'victoria' },
    ],
    caqueta: [
      { label: 'Florencia', value: 'florencia' },
      { label: 'San Vicente del Caguán', value: 'san-vicente-del-caguan' },
      { label: 'Puerto Rico', value: 'puerto-rico' },
      { label: 'La Montañita', value: 'la-montanita' },
      { label: 'Curillo', value: 'curillo' },
      { label: 'El Doncello', value: 'el-doncello' },
      { label: 'El Paujil', value: 'el-paujil' },
      { label: 'Milán', value: 'milan' },
      { label: 'Morelia', value: 'morelia' },
      { label: 'San José del Fragua', value: 'san-jose-del-fragua' },
      { label: 'Solano', value: 'solano' },
      { label: 'Solita', value: 'solita' },
      { label: 'Valparaíso', value: 'valparaiso' },
      { label: 'Belen de los Andaquíes', value: 'belen-de-los-andaquies' },
      { label: 'Peñas Coloradas', value: 'penas-coloradas' },
      { label: 'Tres Esquinas', value: 'tres-esquinas' },
      { label: 'La Unión Peneya', value: 'la-union-peneya' },
      { label: 'Guayabal', value: 'guayabal' },
      { label: 'Santos Cifuentes', value: 'santos-cifuentes' },
      { label: 'Campo Hermoso', value: 'campo-hermoso' },
    ],
    casanare: [
      { label: 'Yopal', value: 'yopal' },
      { label: 'Aguazul', value: 'aguazul' },
      { label: 'Villanueva', value: 'villanueva' },
      { label: 'Tauramena', value: 'tauramena' },
      { label: 'Monterrey', value: 'monterrey' },
      { label: 'Trinidad', value: 'trinidad' },
      { label: 'Paz de Ariporo', value: 'paz-de-ariporo' },
      { label: 'Orocué', value: 'orocue' },
      { label: 'Maní', value: 'mani' },
      { label: 'Nunchía', value: 'nunchia' },
      { label: 'Recetor', value: 'recetor' },
      { label: 'Sabanalarga', value: 'sabanalarga-casanare' },
      { label: 'Chámeza', value: 'chameza' },
      { label: 'San Luis de Palenque', value: 'san-luis-de-palenque' },
      { label: 'Hato Corozal', value: 'hato-corozal' },
      { label: 'La Salina', value: 'la-salina' },
      { label: 'Pore', value: 'pore' },
      { label: 'Támara', value: 'tamara' },
      { label: 'Sacama', value: 'sacama' },
      { label: 'Bocas del Pauto', value: 'bocas-del-pauto' },
    ],
    cauca: [
      { label: 'Popayán', value: 'popayan' },
      { label: 'Santander de Quilichao', value: 'santander-de-quilichao' },
      { label: 'Puerto Tejada', value: 'puerto-tejada' },
      { label: 'Guapi', value: 'guapi' },
      { label: 'El Tambo', value: 'el-tambo' },
      { label: 'Patía', value: 'patia' },
      { label: 'Silvia', value: 'silvia' },
      { label: 'Timbiquí', value: 'timbiqui' },
      { label: 'Suárez', value: 'suarez' },
      { label: 'Cajibío', value: 'cajibio' },
      { label: 'Piendamó', value: 'piendamo' },
      { label: 'Balboa', value: 'balboa' },
      { label: 'Buenos Aires', value: 'buenos-aires' },
      { label: 'Caloto', value: 'caloto' },
      { label: 'Inzá', value: 'inza' },
      { label: 'Jambaló', value: 'jambalo' },
      { label: 'La Sierra', value: 'la-sierra' },
      { label: 'La Vega', value: 'la-vega' },
      { label: 'Mercaderes', value: 'mercaderes' },
      { label: 'Piaguachí', value: 'piaguachi' },
    ],
    cesar: [
      { label: 'Valledupar', value: 'valledupar' },
      { label: 'Aguachica', value: 'aguachica' },
      { label: 'Codazzi', value: 'codazzi' },
      { label: 'La Jagua de Ibirico', value: 'la-jagua-de-ibirico' },
      { label: 'Curumaní', value: 'curumani' },
      { label: 'El Copey', value: 'el-copey' },
      { label: 'Bosconia', value: 'bosconia' },
      { label: 'Chiriguaná', value: 'chiriguana' },
      { label: 'La Paz', value: 'la-paz-cesar' },
      { label: 'Pelaya', value: 'pelaya' },
      { label: 'Pueblo Bello', value: 'pueblo-bello' },
      { label: 'San Alberto', value: 'san-alberto' },
      { label: 'San Diego', value: 'san-diego' },
      { label: 'San Martín', value: 'san-martin' },
      { label: 'Tamalameque', value: 'tamalameque' },
      { label: 'Astrea', value: 'astrea' },
      { label: 'Gamarra', value: 'gamarra' },
      { label: 'González', value: 'gonzalez' },
      { label: 'Manaure Balcón del Cesar', value: 'manaure' },
      { label: 'Río de Oro', value: 'rio-de-oro' },
    ],
    choco: [
      { label: 'Quibdó', value: 'quibdo' },
      { label: 'Istmina', value: 'istmina' },
      { label: 'Condoto', value: 'condoto' },
      { label: 'Tadó', value: 'tado' },
      { label: 'Medio San Juan', value: 'medio-san-juan' },
      { label: 'Bajo Baudó', value: 'bajo-baudo' },
      { label: 'Acandí', value: 'acandi' },
      { label: 'Unguía', value: 'ungua' },
      { label: 'El Carmen de Atrato', value: 'el-carmen-de-atrato' },
      { label: 'Lloró', value: 'lloro' },
      { label: 'Bahía Solano', value: 'bahia-solano' },
      { label: 'Nuquí', value: 'nuqui' },
      { label: 'Riosucio', value: 'riosucio-choco' },
      { label: 'Sipí', value: 'sipi' },
      { label: 'Juradó', value: 'jurado' },
      { label: 'Medio Atrato', value: 'medio-atrato' },
      { label: 'Medio Baudó', value: 'medio-baudo' },
      { label: 'Alto Baudó', value: 'alto-baudo' },
      { label: 'San José del Palmar', value: 'san-jose-del-palmar' },
      { label: 'Cértegui', value: 'certegui' },
    ],
    cordoba: [
      { label: 'Montería', value: 'monteria' },
      { label: 'Lorica', value: 'lorica' },
      { label: 'Cereté', value: 'cerete' },
      { label: 'Sahagún', value: 'sahagun' },
      { label: 'Montelíbano', value: 'montelibano' },
      { label: 'Tierralta', value: 'tierralta' },
      { label: 'Planeta Rica', value: 'planeta-rica' },
      { label: 'San Antero', value: 'san-antero' },
      { label: 'Puerto Escondido', value: 'puerto-escondido' },
      { label: 'San Pelayo', value: 'san-pelayo' },
      { label: 'San Bernardo del Viento', value: 'san-bernardo-del-viento' },
      { label: 'Cotorra', value: 'cotorra' },
      { label: 'Chinú', value: 'chinu' },
      { label: 'Moñitos', value: 'monitos' },
      { label: 'Ayapel', value: 'ayapel' },
      { label: 'Buenavista', value: 'buenavista' },
      { label: 'Valencia', value: 'valencia' },
      { label: 'Puerto Libertador', value: 'puerto-libertador' },
      { label: 'La Apartada', value: 'la-apartada' },
      { label: 'San José de Uré', value: 'san-jose-de-ure' },
    ],
    cundinamarca: [
      { label: 'Bogotá', value: 'bogota' },
      { label: 'Soacha', value: 'soacha' },
      { label: 'Chía', value: 'chia' },
      { label: 'Zipaquirá', value: 'zipaquira' },
      { label: 'Facatativá', value: 'facatativa' },
      { label: 'Girardot', value: 'girardot' },
      { label: 'Mosquera', value: 'mosquera' },
      { label: 'Funza', value: 'funza' },
      { label: 'Madrid', value: 'madrid' },
      { label: 'Cajicá', value: 'cajica' },
      { label: 'La Calera', value: 'la-calera' },
      { label: 'Tabio', value: 'tabio' },
      { label: 'Tenjo', value: 'tenjo' },
      { label: 'Villeta', value: 'villeta' },
      { label: 'Fusagasugá', value: 'fusagasuga' },
      { label: 'Guaduas', value: 'guaduas' },
      { label: 'Cota', value: 'cota' },
      { label: 'Tocancipá', value: 'tocancipa' },
      { label: 'Ubaté', value: 'ubate' },
      { label: 'Anapoima', value: 'anapoima' },
    ],
    guainia: [
      { label: 'Inírida', value: 'inírida' },
      { label: 'Barranco Minas', value: 'barranco-minas' },
      { label: 'Mapiripana', value: 'mapiripana' },
      { label: 'San Felipe', value: 'san-felipe' },
      { label: 'Puerto Colombia', value: 'puerto-colombia-guainia' },
      { label: 'La Guadalupe', value: 'la-guadalupe' },
      { label: 'Cacahual', value: 'cacahual' },
      { label: 'Pana Pana', value: 'pana-pana' },
      { label: 'Morichal', value: 'morichal' },
      { label: 'Sierra de La Macarena', value: 'sierra-de-la-macarena' },
      { label: 'San José de Guaviare', value: 'san-jose-guaviare' },
      { label: 'Tonina', value: 'tonina' },
      { label: 'La Ceiba', value: 'la-ceiba' },
      { label: 'Morichal Viejo', value: 'morichal-viejo' },
      { label: 'Puerto Inírida', value: 'puerto-inirida' },
      { label: 'Caño Bocón', value: 'cano-bocon' },
      { label: 'El Remanso', value: 'el-remanso' },
      { label: 'Chaparralito', value: 'chaparralito' },
      { label: 'Cachicamo', value: 'cachicamo' },
      { label: 'El Coco', value: 'el-coco' },
    ],
    guaviare: [
      { label: 'San José del Guaviare', value: 'san-jose-del-guaviare' },
      { label: 'Calamar', value: 'calamar-guaviare' },
      { label: 'El Retorno', value: 'el-retorno' },
      { label: 'Miraflores', value: 'miraflores-guaviare' },
      { label: 'Charras', value: 'charras' },
      { label: 'La Libertad', value: 'la-libertad-guaviare' },
      { label: 'El Capricho', value: 'el-capricho' },
      { label: 'Puerto Arturo', value: 'puerto-arturo' },
      { label: 'Platanillo', value: 'platanillo' },
      { label: 'La Paz', value: 'la-paz-guaviare' },
      { label: 'Guayabero', value: 'guayabero' },
      { label: 'Nueva Antioquia', value: 'nueva-antioquia' },
      { label: 'Caño Lajas', value: 'cano-lajas' },
      { label: 'Puerto Nuevo', value: 'puerto-nuevo' },
      { label: 'Charras Boquerón', value: 'charras-boqueron' },
      { label: 'Puerto Golondrina', value: 'puerto-golondrina' },
      { label: 'Macarena', value: 'macarena-guaviare' },
      { label: 'La Carpa', value: 'la-carpa' },
      { label: 'El Tigre', value: 'el-tigre' },
      { label: 'Caño Negro', value: 'cano-negro' },
    ],
    huila: [
      { label: 'Neiva', value: 'neiva' },
      { label: 'Pitalito', value: 'pitalito' },
      { label: 'Garzón', value: 'garzon' },
      { label: 'La Plata', value: 'la-plata' },
      { label: 'Campoalegre', value: 'campoalegre' },
      { label: 'Aipe', value: 'aipe' },
      { label: 'Isnos', value: 'isnos' },
      { label: 'San Agustín', value: 'san-agustin' },
      { label: 'Paicol', value: 'paicol' },
      { label: 'Gigante', value: 'gigante' },
      { label: 'Tello', value: 'tello' },
      { label: 'Villavieja', value: 'villavieja' },
      { label: 'Baraya', value: 'baraya' },
      { label: 'Tesalia', value: 'tesalia' },
      { label: 'Yaguará', value: 'yaguara' },
      { label: 'Palermo', value: 'palermo' },
      { label: 'Altamira', value: 'altamira' },
      { label: 'Rivera', value: 'rivera' },
      { label: 'Santa María', value: 'santa-maria' },
      { label: 'Elías', value: 'elias' },
    ],
    la_guajira: [
      { label: 'Riohacha', value: 'riohacha' },
      { label: 'Maicao', value: 'maicao' },
      { label: 'Uribia', value: 'uribia' },
      { label: 'Manaure', value: 'manaure' },
      { label: 'San Juan del Cesar', value: 'san-juan-del-cesar' },
      { label: 'Fonseca', value: 'fonseca' },
      { label: 'Villanueva', value: 'villanueva-guajira' },
      { label: 'El Molino', value: 'el-molino' },
      { label: 'Barrancas', value: 'barrancas' },
      { label: 'Dibulla', value: 'dibulla' },
      { label: 'La Jagua del Pilar', value: 'la-jagua-del-pilar' },
      { label: 'Distracción', value: 'distraccion' },
      { label: 'Hatonuevo', value: 'hatonuevo' },
      { label: 'Urumita', value: 'urumita' },
      { label: 'Albania', value: 'albania' },
      { label: 'Campana', value: 'campana' },
      { label: 'Tomarrazón', value: 'tomarrazon' },
      { label: 'Choles', value: 'choles' },
      { label: 'Mingueo', value: 'mingueo' },
      { label: 'Carraipía', value: 'carraipia' },
    ],
    magdalena: [
      { label: 'Santa Marta', value: 'santa-marta' },
      { label: 'Ciénaga', value: 'cienaga' },
      { label: 'Fundación', value: 'fundacion' },
      { label: 'Aracataca', value: 'aracataca' },
      { label: 'El Banco', value: 'el-banco' },
      { label: 'Plato', value: 'plato' },
      { label: 'Pivijay', value: 'pivijay' },
      { label: 'Zona Bananera', value: 'zona-bananera' },
      { label: 'San Sebastián de Buenavista', value: 'san-sebastian-de-buenavista' },
      { label: 'Santa Ana', value: 'santa-ana' },
      { label: 'Guamal', value: 'guamal' },
      { label: 'Sabanas de San Ángel', value: 'sabanas-de-san-angel' },
      { label: 'Remolino', value: 'remolino' },
      { label: 'El Piñón', value: 'el-pinon' },
      { label: 'Sitio Nuevo', value: 'sitio-nuevo' },
      { label: 'Tenerife', value: 'tenerife' },
      { label: 'Nueva Granada', value: 'nueva-granada' },
      { label: 'Pueblo Viejo', value: 'pueblo-viejo' },
      { label: 'Zapayán', value: 'zapayan' },
      { label: 'San Zenón', value: 'san-zenon' },
    ],
    meta: [
      { label: 'Villavicencio', value: 'villavicencio' },
      { label: 'Acacías', value: 'acacias' },
      { label: 'Granada', value: 'granada' },
      { label: 'Puerto López', value: 'puerto-lopez' },
      { label: 'San Martín', value: 'san-martin-meta' },
      { label: 'Puerto Gaitán', value: 'puerto-gaitan' },
      { label: 'Cumaral', value: 'cumaral' },
      { label: 'Restrepo', value: 'restrepo' },
      { label: 'Castilla La Nueva', value: 'castilla-la-nueva' },
      { label: 'Guamal', value: 'guamal-meta' },
      { label: 'Cabuyaro', value: 'cabuyaro' },
      { label: 'El Dorado', value: 'el-dorado' },
      { label: 'Fuente de Oro', value: 'fuente-de-oro' },
      { label: 'San Carlos de Guaroa', value: 'san-carlos-de-guaroa' },
      { label: 'San Juan de Arama', value: 'san-juan-de-arama' },
      { label: 'Puerto Concordia', value: 'puerto-concordia' },
      { label: 'Puerto Rico', value: 'puerto-rico-meta' },
      { label: 'Lejanías', value: 'lejanias' },
      { label: 'Mapiripán', value: 'mapiripan' },
      { label: 'Uribe', value: 'uribe' },
    ],
    narino: [
      { label: 'Pasto', value: 'pasto' },
      { label: 'Ipiales', value: 'ipiales' },
      { label: 'Tumaco', value: 'tumaco' },
      { label: 'Túquerres', value: 'tuquerres' },
      { label: 'Sandoná', value: 'sandona' },
      { label: 'La Unión', value: 'la-union' },
      { label: 'Guachucal', value: 'guachucal' },
      { label: 'Consacá', value: 'consaca' },
      { label: 'Cumbal', value: 'cumbal' },
      { label: 'Aldana', value: 'aldana' },
      { label: 'Pupiales', value: 'pupiales' },
      { label: 'Sapuyes', value: 'sapuyes' },
      { label: 'Samaniego', value: 'samaniego' },
      { label: 'Chachagüí', value: 'chachagui' },
      { label: 'El Tambo', value: 'el-tambo-narino' },
      { label: 'Policarpa', value: 'policarpa' },
      { label: 'Guaitarilla', value: 'guaitarilla' },
      { label: 'Olaya Herrera', value: 'olaya-herrera' },
      { label: 'La Cruz', value: 'la-cruz' },
      { label: 'El Peñol', value: 'el-penol' },
    ],
    norte_de_santander: [
      { label: 'Cúcuta', value: 'cucuta' },
      { label: 'Ocaña', value: 'ocana' },
      { label: 'Pamplona', value: 'pamplona' },
      { label: 'Villa del Rosario', value: 'villa-del-rosario' },
      { label: 'Los Patios', value: 'los-patios' },
      { label: 'El Zulia', value: 'el-zulia' },
      { label: 'Ábrego', value: 'abrego' },
      { label: 'Tibú', value: 'tibu' },
      { label: 'Chinácota', value: 'chinacota' },
      { label: 'Convención', value: 'convencion' },
      { label: 'Sardinata', value: 'sardinata' },
      { label: 'La Playa de Belén', value: 'la-playa-de-belen' },
      { label: 'Bochalema', value: 'bochalema' },
      { label: 'El Tarra', value: 'el-tarra' },
      { label: 'Gramalote', value: 'gramalote' },
      { label: 'San Calixto', value: 'san-calixto' },
      { label: 'Teorama', value: 'teorama' },
      { label: 'El Carmen', value: 'el-carmen' },
      { label: 'Durania', value: 'durania' },
      { label: 'Mutiscua', value: 'mutiscua' },
    ],
    putumayo: [
      { label: 'Mocoa', value: 'mocoa' },
      { label: 'Puerto Asís', value: 'puerto-asis' },
      { label: 'Orito', value: 'orito' },
      { label: 'Villagarzón', value: 'villagarzon' },
      { label: 'Puerto Guzmán', value: 'puerto-guzman' },
      { label: 'San Francisco', value: 'san-francisco' },
      { label: 'Sibundoy', value: 'sibundoy' },
      { label: 'Colón', value: 'colon' },
      { label: 'Valle del Guamuez', value: 'valle-del-guamuez' },
      { label: 'San Miguel', value: 'san-miguel' },
      { label: 'Puerto Caicedo', value: 'puerto-caicedo' },
      { label: 'Puerto Leguízamo', value: 'puerto-leguizamo' },
      { label: 'El Pepino', value: 'el-pepino' },
      { label: 'Villaflor', value: 'villaflor' },
      { label: 'Alto Putumayo', value: 'alto-putumayo' },
      { label: 'Yunguillo', value: 'yunguillo' },
      { label: 'Nueva Esperanza', value: 'nueva-esperanza' },
      { label: 'La Dorada', value: 'la-dorada-putumayo' },
      { label: 'San Pedro', value: 'san-pedro-putumayo' },
      { label: 'El Placer', value: 'el-placer' },
    ],
    quindio: [
      { label: 'Armenia', value: 'armenia' },
      { label: 'Calarcá', value: 'calarca' },
      { label: 'Montenegro', value: 'montenegro' },
      { label: 'La Tebaida', value: 'la-tebaida' },
      { label: 'Quimbaya', value: 'quimbaya' },
      { label: 'Filandia', value: 'filandia' },
      { label: 'Salento', value: 'salento' },
      { label: 'Circasia', value: 'circasia' },
      { label: 'Buenavista', value: 'buenavista-quindio' },
      { label: 'Génova', value: 'genova' },
      { label: 'Barcelona', value: 'barcelona' },
      { label: 'Pueblo Tapao', value: 'pueblo-tapao' },
      { label: 'El Caimo', value: 'el-caimo' },
      { label: 'La Silvia', value: 'la-silvia' },
      { label: 'La India', value: 'la-india' },
      { label: 'Córdoba', value: 'cordoba-quindio' },
      { label: 'San Juan de Carolina', value: 'san-juan-carolina' },
      { label: 'Chagualá', value: 'chaguala' },
      { label: 'El Edén', value: 'el-eden' },
      { label: 'Quebradanegra', value: 'quebradanegra' },
    ],
    risaralda: [
      { label: 'Pereira', value: 'pereira' },
      { label: 'Dosquebradas', value: 'dosquebradas' },
      { label: 'Santa Rosa de Cabal', value: 'santa-rosa-de-cabal' },
      { label: 'La Virginia', value: 'la-virginia' },
      { label: 'Apía', value: 'apia' },
      { label: 'Belén de Umbría', value: 'belen-de-umbria' },
      { label: 'Marsella', value: 'marsella' },
      { label: 'Santuario', value: 'santuario' },
      { label: 'Quinchía', value: 'quinchia' },
      { label: 'Mistrató', value: 'mistrato' },
      { label: 'Guática', value: 'guatica' },
      { label: 'Balboa', value: 'balboa-risaralda' },
      { label: 'La Celia', value: 'la-celia' },
      { label: 'Combia', value: 'combia' },
      { label: 'Caimalito', value: 'caimalito' },
      { label: 'Villa Santana', value: 'villa-santana' },
      { label: 'Morelia', value: 'morelia-risaralda' },
      { label: 'El Jazmín', value: 'el-jazmin' },
      { label: 'Pio XII', value: 'pio-xii' },
      { label: 'Altagracia', value: 'altagracia' },
    ],
    san_andres: [
      { label: 'San Andrés', value: 'san-andres' },
      { label: 'Providencia', value: 'providencia' },
      { label: 'Santa Catalina', value: 'santa-catalina' },
      { label: 'La Loma', value: 'la-loma' },
      { label: 'San Luis', value: 'san-luis' },
      { label: 'Cove', value: 'cove' },
      { label: 'Rocky Cay', value: 'rocky-cay' },
      { label: 'Sarie Bay', value: 'sarie-bay' },
      { label: 'Sound Bay', value: 'sound-bay' },
      { label: 'La Piscinita', value: 'la-piscinita' },
      { label: 'El Cove', value: 'el-cove' },
      { label: 'Pueblo Viejo', value: 'pueblo-viejo-san-andres' },
      { label: 'Orange Hill', value: 'orange-hill' },
      { label: 'Hill Point', value: 'hill-point' },
      { label: 'San Felipe', value: 'san-felipe-san-andres' },
      { label: 'Almendros', value: 'almendros' },
      { label: 'North End', value: 'north-end' },
      { label: 'La Rocosa', value: 'la-rocosa' },
      { label: 'Elsy Bar', value: 'elsy-bar' },
      { label: 'Loma Barrington', value: 'loma-barrington' },
    ],
    santander: [
      { label: 'Bucaramanga', value: 'bucaramanga' },
      { label: 'Floridablanca', value: 'floridablanca' },
      { label: 'Girón', value: 'giron' },
      { label: 'Piedecuesta', value: 'piedecuesta' },
      { label: 'Barrancabermeja', value: 'barrancabermeja' },
      { label: 'San Gil', value: 'san-gil' },
      { label: 'Socorro', value: 'socorro' },
      { label: 'Lebrija', value: 'lebrija' },
      { label: 'Málaga', value: 'malaga' },
      { label: 'Barichara', value: 'barichara' },
      { label: 'Charalá', value: 'charala' },
      { label: 'Zapatoca', value: 'zapatoca' },
      { label: 'Vélez', value: 'velez' },
      { label: 'El Carmen de Chucurí', value: 'el-carmen-de-chucuri' },
      { label: 'Puerto Wilches', value: 'puerto-wilches' },
      { label: 'Cimitarra', value: 'cimitarra' },
      { label: 'San Vicente de Chucurí', value: 'san-vicente-de-chucuri' },
      { label: 'Rionegro', value: 'rionegro-santander' },
      { label: 'Onzaga', value: 'onzaga' },
      { label: 'Guapotá', value: 'guapota' },
    ],
    sucre: [
      { label: 'Sincelejo', value: 'sincelejo' },
      { label: 'Corozal', value: 'corozal' },
      { label: 'Sampués', value: 'sampues' },
      { label: 'San Marcos', value: 'san-marcos' },
      { label: 'Tolú', value: 'tolu' },
      { label: 'Coveñas', value: 'covenas' },
      { label: 'San Onofre', value: 'san-onofre' },
      { label: 'Morroa', value: 'morroa' },
      { label: 'Galeras', value: 'galeras' },
      { label: 'Los Palmitos', value: 'los-palmitos' },
      { label: 'Majagual', value: 'majagual' },
      { label: 'Ovejas', value: 'ovejas' },
      { label: 'Colosó', value: 'coloso' },
      { label: 'San Pedro', value: 'san-pedro-sucre' },
      { label: 'San Benito Abad', value: 'san-benito-abad' },
      { label: 'El Roble', value: 'el-roble' },
      { label: 'Guaranda', value: 'guaranda' },
      { label: 'Chalán', value: 'chalan' },
      { label: 'Buenavista', value: 'buenavista-sucre' },
      { label: 'Caimito', value: 'caimito' },
    ],
    tolima: [
      { label: 'Ibagué', value: 'ibague' },
      { label: 'Espinal', value: 'espinal' },
      { label: 'Melgar', value: 'melgar' },
      { label: 'Honda', value: 'honda' },
      { label: 'Mariquita', value: 'mariquita' },
      { label: 'Chaparral', value: 'chaparral' },
      { label: 'Líbano', value: 'libano' },
      { label: 'Purificación', value: 'purificacion' },
      { label: 'Guamo', value: 'guamo' },
      { label: 'Flandes', value: 'flandes' },
      { label: 'Cajamarca', value: 'cajamarca' },
      { label: 'Natagaima', value: 'natagaima' },
      { label: 'Rovira', value: 'rovira' },
      { label: 'Ortega', value: 'ortega' },
      { label: 'Saldaña', value: 'saldana' },
      { label: 'Icononzo', value: 'icononzo' },
      { label: 'Villarrica', value: 'villarrica' },
      { label: 'Anzoátegui', value: 'anzoategui' },
      { label: 'Alpujarra', value: 'alpujarra' },
      { label: 'Ataco', value: 'ataco' },
    ],
    valle_del_cauca: [
      { label: 'Cali', value: 'cali' },
      { label: 'Palmira', value: 'palmira' },
      { label: 'Buenaventura', value: 'buenaventura' },
      { label: 'Buga', value: 'buga' },
      { label: 'Tuluá', value: 'tulua' },
      { label: 'Cartago', value: 'cartago' },
      { label: 'Jamundí', value: 'jamundi' },
      { label: 'Yumbo', value: 'yumbo' },
      { label: 'Florida', value: 'florida' },
      { label: 'Pradera', value: 'pradera' },
      { label: 'Candelaria', value: 'candelaria-valle' },
      { label: 'Roldanillo', value: 'roldanillo' },
      { label: 'Zarzal', value: 'zarzal' },
      { label: 'Sevilla', value: 'sevilla' },
      { label: 'Caicedonia', value: 'caicedonia' },
      { label: 'La Unión', value: 'la-union-valle' },
      { label: 'Obando', value: 'obando' },
      { label: 'El Cerrito', value: 'el-cerrito' },
      { label: 'La Victoria', value: 'la-victoria-valle' },
      { label: 'Andalucía', value: 'andalucia' },
    ],
    vaupes: [
      { label: 'Mitú', value: 'mitu' },
      { label: 'Carurú', value: 'caruru' },
      { label: 'Taraira', value: 'taraira' },
      { label: 'Pacoa', value: 'pacoa' },
      { label: 'Papunaua', value: 'papunaua' },
      { label: 'Yavaraté', value: 'yavarate' },
      { label: 'Villa Fátima', value: 'villa-fatima' },
      { label: 'Cumaribo Mitú', value: 'cumaribo-mitu' },
      { label: 'Bocas del Taraira', value: 'bocas-del-taraira' },
      { label: 'Caño Colorado', value: 'cano-colorado' },
      { label: 'Puerto Golondrina', value: 'puerto-golondrina-vaupes' },
      { label: 'Villa Nueva', value: 'villa-nueva' },
      { label: 'Morichal', value: 'morichal-vaupes' },
      { label: 'Santa Cruz', value: 'santa-cruz-vaupes' },
      { label: 'Campo Alegre', value: 'campo-alegre-vaupes' },
      { label: 'San Luis', value: 'san-luis-vaupes' },
      { label: 'San José del Vaupés', value: 'san-jose-vaupes' },
      { label: 'La Libertad', value: 'la-libertad-vaupes' },
      { label: 'Cumaribo Taraira', value: 'cumaribo-taraira' },
      { label: 'Santa Rita', value: 'santa-rita-vaupes' },
    ],
    vichada: [
      { label: 'Puerto Carreño', value: 'puerto-carreno' },
      { label: 'La Primavera', value: 'la-primavera' },
      { label: 'Santa Rosalía', value: 'santa-rosalia' },
      { label: 'Cumaribo', value: 'cumaribo' },
      { label: 'San José de Ocune', value: 'san-jose-de-ocune' },
      { label: 'Guafal', value: 'guafal' },
      { label: 'Chupave', value: 'chupave' },
      { label: 'Aceitico', value: 'aceitico' },
      { label: 'Morichal Viejo', value: 'morichal-viejo-vichada' },
      { label: 'Santa Bárbara', value: 'santa-barbara-vichada' },
      { label: 'Mata de Gallina', value: 'mata-de-gallina' },
      { label: 'Puerto Nariño', value: 'puerto-narino-vichada' },
      { label: 'Pacu', value: 'pacu' },
      { label: 'Puerto Nuevo', value: 'puerto-nuevo-vichada' },
      { label: 'Guacacías', value: 'guacacias' },
      { label: 'El Viento', value: 'el-viento' },
      { label: 'La Venturosa', value: 'la-venturosa' },
      { label: 'Maitá', value: 'maita' },
      { label: 'Campo Alegre', value: 'campo-alegre-vichada' },
      { label: 'Morrocoy', value: 'morrocoy' },
    ],
    bogota: [
      { label: 'Usaquén', value: 'usaquen' },
      { label: 'Chapinero', value: 'chapinero' },
      { label: 'Santa Fe', value: 'santa-fe' },
      { label: 'San Cristóbal', value: 'san-cristobal' },
      { label: 'Usme', value: 'usme' },
      { label: 'Tunjuelito', value: 'tunjuelito' },
      { label: 'Bosa', value: 'bosa' },
      { label: 'Kennedy', value: 'kennedy' },
      { label: 'Fontibón', value: 'fontibon' },
      { label: 'Engativá', value: 'engativa' },
      { label: 'Suba', value: 'suba' },
      { label: 'Barrios Unidos', value: 'barrios-unidos' },
      { label: 'Teusaquillo', value: 'teusaquillo' },
      { label: 'Mártires', value: 'martires' },
      { label: 'Antonio Nariño', value: 'antonio-narino' },
      { label: 'Puente Aranda', value: 'puente-aranda' },
      { label: 'Candelaria', value: 'candelaria' },
      { label: 'Rafael Uribe Uribe', value: 'rafael-uribe' },
      { label: 'Ciudad Bolívar', value: 'ciudad-bolivar' },
      { label: 'Sumapaz', value: 'sumapaz' },
    ]
  }

  const ciudadOptions = ref<SelectOption[]>([])

  const updateCiudadesByDepartamento = (departamentoValue: string) => {
    ciudadOptions.value = municipiosPorDepartamento[departamentoValue] || []
  }

  return {
    tipoOptions: readonly(tipoOptionsState),
    isLoadingTipos: readonly(isLoadingTipos),
    tiposError: readonly(tiposError),
    isSubmitting: readonly(isSubmitting),
    feedbackMessage: readonly(feedbackMessage),
    departamentoOptions: readonly(departamentoOptions),
    ciudadOptions: readonly(ciudadOptions),
    loadTiposDocumento,
    updateCiudadesByDepartamento,
    submit
  }
}