name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.vue'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.*'
      - 'src-tauri/**'

jobs:
  build-windows-exe:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      # Build only the executable (no MSI/installer) to avoid WiX/NSIS deps
      - name: Build Tauri binary (release)
        working-directory: src-tauri
        run: cargo build --release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo-windows-exe
          path: src-tauri/target/release/demo.exe

